/* Corrêa Controle Interno — Dados editáveis da aplicação. */
window.CorreaData = {
  clients: [
    { name: 'Aderci Kemper', cnpj: '42.910.621/0001-52', city: 'Imbituba', tax: 'MEI', activity: 'Comercio', payroll: 'Não', active: true, initials: 'AK', tone: 'peach' },
    { name: 'Apache', cnpj: '64.992.421/0001-29', city: 'Imbituba', tax: 'SIMPLES', activity: 'Serviço', payroll: 'Sim', active: true, initials: 'AP', tone: 'peach' },
    { name: 'Aguiar Castro E Fermino', cnpj: '53.903.158/0001-38', city: 'Imbituba', tax: 'SIMPLES', activity: 'Serviço', payroll: 'Não', active: true, initials: 'AC', tone: 'blue' },
    { name: 'Andrezza Fontanella', cnpj: '64.572.600/0001-07', city: 'Imbituba', tax: 'SIMPLES', activity: 'Serviço', payroll: 'Sim', active: true, initials: 'AF', tone: 'mint' },
    { name: 'Alex Estamparia', cnpj: '49.616.710/0001-30', city: 'Garopaba', tax: 'SIMPLES', activity: 'Comercio', payroll: 'Sim', active: true, initials: 'AE', tone: 'sand' },
    { name: 'Amanda - Injecar', cnpj: '58.436.860/0001-52', city: 'Imbituba', tax: 'SIMPLES', activity: 'Comércio E Serviço', payroll: 'Não', active: true, initials: 'A-', tone: '' },
    { name: 'André - Zeladoria', cnpj: '41.439.204/0001-00', city: 'Imbituba', tax: 'MEI', activity: 'Serviço', payroll: 'Não', active: true, initials: 'A-', tone: 'peach' },
    { name: 'Amai', cnpj: '17.594.323/0001-53', city: 'Imbituba', tax: 'PRESUMIDO', activity: 'Associação', payroll: 'Sim', active: true, initials: 'AM', tone: 'blue' },
    { name: 'Arlei Soares', cnpj: '60.783.407/0001-64', city: 'Imbituba', tax: 'MEI', activity: 'Comercio', payroll: 'Não', active: true, initials: 'AS', tone: 'peach' },
    { name: 'Batista Manutenções', cnpj: '46.916.890/0001-87', city: 'Imbituba', tax: 'SIMPLES', activity: 'Serviço', payroll: 'Sim', active: true, initials: 'BM', tone: 'sand' },
    { name: 'Bem Mulher Cosméticos', cnpj: '28.420.175/0001-77', city: 'Balneario Camboriu', tax: 'SIMPLES', activity: 'Comercio', payroll: 'Sim', active: true, initials: 'BM', tone: '' },
    { name: 'Bernardi Construções', cnpj: '62.204.616/0001-31', city: 'Imbituba', tax: 'SIMPLES', activity: 'Serviço', payroll: 'Não', active: true, initials: 'BC', tone: 'peach' },
    { name: 'Bruna Vieira De Souza', cnpj: '67.267.669/0001-15', city: 'Imbituba', tax: 'SIMPLES', activity: 'Serviço', payroll: 'Sim', active: true, initials: 'BV', tone: 'blue' },
    { name: 'B7 Mix', cnpj: '27.430.417/0001-40', city: 'Imbituba', tax: 'SIMPLES', activity: 'Comércio E Serviço', payroll: 'Sim', active: true, initials: 'BM', tone: 'mint' },
    { name: 'Box M.A', cnpj: '44.604.328/0001-92', city: 'Imbituba', tax: 'SIMPLES', activity: 'Comércio E Serviço', payroll: 'Sim', active: true, initials: 'BM', tone: 'sand' },
    { name: 'Box 15', cnpj: '53.052.108/0001-94', city: 'Imbituba', tax: 'SIMPLES', activity: 'Comercio', payroll: 'Sim', active: true, initials: 'B1', tone: '' },
    { name: 'Centralis', cnpj: '45.766.620/0001-74', city: 'Imbituba', tax: 'SIMPLES', activity: 'Serviço', payroll: 'Sim', active: true, initials: 'CE', tone: 'peach' },
    { name: 'Centro De Treinamento Cominesi', cnpj: '48.908.393/0001-62', city: 'Imbituba', tax: 'SIMPLES', activity: 'Serviço', payroll: 'Sim', active: true, initials: 'CD', tone: 'blue' },
    { name: 'Colonia De Pescadores', cnpj: '82.909.227/0001-19', city: 'Imbituba', tax: 'PRESUMIDO', activity: 'Associação', payroll: 'Sim', active: true, initials: 'CD', tone: 'mint' },
    { name: 'Cooperimtra', cnpj: '10.266.189/0001-12', city: 'Imbituba', tax: 'PRESUMIDO', activity: 'Comércio E Serviço', payroll: 'Sim', active: true, initials: 'CO', tone: 'sand' },
    { name: 'Correa Assessoria', cnpj: '51.528.929/0001-29', city: 'Imbituba', tax: 'SIMPLES', activity: 'Serviço', payroll: 'Sim', active: true, initials: 'CA', tone: '' },
    { name: 'Dalana Lanches', cnpj: '43.987.712/0001-59', city: 'Imbituba', tax: 'SIMPLES', activity: 'Comércio E Serviço', payroll: 'Não', active: true, initials: 'DL', tone: 'peach' },
    { name: 'Dilson Petrassem', cnpj: '57.884.924/0001-15', city: 'Imbituba', tax: 'MEI', activity: 'Serviço', payroll: 'Não', active: true, initials: 'DP', tone: 'peach' },
    { name: 'Douglas - Ana Loja', cnpj: '51.842.314/0001-72', city: 'Imbituba', tax: 'MEI', activity: 'Comercio', payroll: 'Não', active: true, initials: 'D-', tone: 'peach' },
    { name: 'Dunas Restaurante', cnpj: '42.701.678/0001-41', city: 'Imbituba', tax: 'SIMPLES', activity: 'Comercio', payroll: 'Não', active: true, initials: 'DR', tone: 'sand' },
    { name: 'Epacom', cnpj: '14.009.323/0001-50', city: 'Balneario Camboriu', tax: 'SIMPLES', activity: 'Comércio E Serviço', payroll: 'Não', active: true, initials: 'EP', tone: '' },
    { name: 'Eduarda Garcia - Cnpj', cnpj: '50.962.336/0001-03', city: 'Imbituba', tax: 'MEI', activity: 'Comercio', payroll: 'Não', active: true, initials: 'EG', tone: 'peach' },
    { name: 'Eduarda Garcia - Psico', cnpj: '10373757930.0', city: 'Imbituba', tax: 'Pf', activity: 'Pessoa Fisica', payroll: 'Não', active: true, initials: 'EG', tone: 'blue' },
    { name: 'Fabi Perfumaria', cnpj: '53.449.837/0001-89', city: 'Imbituba', tax: 'SIMPLES', activity: 'Comercio', payroll: 'Sim', active: true, initials: 'FP', tone: 'mint' },
    { name: 'Fb Esportes', cnpj: '65.065.400/0001-20', city: 'Imbituba', tax: 'SIMPLES', activity: 'Serviço', payroll: 'Não', active: true, initials: 'FE', tone: 'sand' },
    { name: 'Fabio Martins - Duda Baby', cnpj: '54.458.517/0001-58', city: 'Imbituba', tax: 'SIMPLES', activity: 'Comercio', payroll: 'Sim', active: true, initials: 'FM', tone: '' },
    { name: 'Gavivias', cnpj: '28.151.091/0001-85', city: 'Imbituba', tax: 'SIMPLES', activity: 'Comércio E Serviço', payroll: 'Sim', active: true, initials: 'GA', tone: 'peach' },
    { name: 'Geovane Benvenuti', cnpj: '32.148.822/0001-00', city: 'Laguna', tax: 'SIMPLES', activity: 'Comercio', payroll: 'Não', active: true, initials: 'GB', tone: 'blue' },
    { name: 'Guilherme Roque', cnpj: '60.103.395/0001-80', city: 'Imbituba', tax: 'SIMPLES', activity: 'Serviço', payroll: 'Sim', active: true, initials: 'GR', tone: 'mint' },
    { name: 'Gilmara', cnpj: '59.410.742/0001-38', city: 'Imbituba', tax: 'MEI', activity: 'Comercio', payroll: 'Sim', active: true, initials: 'GI', tone: 'peach' },
    { name: 'Helena Comeli', cnpj: '61.816.158/0001-29', city: 'Imbituba', tax: 'SIMPLES', activity: 'Comércio E Serviço', payroll: 'Não', active: true, initials: 'HC', tone: '' },
    { name: 'Herminio Móveis', cnpj: '32.709.790/0001-75', city: 'Imbituba', tax: 'PRESUMIDO', activity: 'Comercio', payroll: 'Não', active: true, initials: 'HM', tone: 'peach' },
    { name: 'Herminio Móveis - Cnpj Novo', cnpj: '63.042.674/0001-79', city: 'Imbituba', tax: 'SIMPLES', activity: 'Comercio', payroll: 'Não', active: true, initials: 'HM', tone: 'blue' },
    { name: 'Hubox Logistica', cnpj: '67.695.463/0001-96', city: 'Imbituba', tax: 'SIMPLES', activity: 'Comércio E Serviço', payroll: 'Não', active: true, initials: 'HL', tone: 'mint' },
    { name: 'Hiper Cell', cnpj: '35.681.914/0001-40', city: 'Imbituba', tax: 'SIMPLES', activity: 'Comércio E Serviço', payroll: 'Não', active: true, initials: 'HC', tone: 'sand' },
    { name: 'Imbiseg', cnpj: '51.362.824/0001-42', city: 'Imbituba', tax: 'SIMPLES', activity: 'Comércio E Serviço', payroll: 'Não', active: true, initials: 'IM', tone: '' },
    { name: 'Isadora', cnpj: '09394649930', city: 'Imbituba', tax: 'Pf', activity: 'Pessoa Fisica', payroll: 'Não', active: true, initials: 'IS', tone: 'peach' },
    { name: 'Josiel - Estelaine', cnpj: '35.388.239/0001-65', city: 'Imbituba', tax: 'SIMPLES', activity: 'Comércio E Serviço', payroll: 'Sim', active: true, initials: 'J-', tone: 'blue' },
    { name: 'Josias Borracharia', cnpj: '51.133.238/0001-26', city: 'Imbituba', tax: 'SIMPLES', activity: 'Comércio E Serviço', payroll: 'Sim', active: true, initials: 'JB', tone: 'mint' },
    { name: 'Jose Carlos', cnpj: '63.277.747/0001-01', city: 'Florianopolis', tax: 'SIMPLES', activity: 'Comércio E Serviço', payroll: 'Não', active: true, initials: 'JC', tone: 'sand' },
    { name: 'Laura Gomes', cnpj: '35.349.577/0001-98', city: 'Tubarão', tax: 'MEI', activity: 'Comercio', payroll: 'Não', active: true, initials: 'LG', tone: 'peach' },
    { name: 'Leonardo Rodrigues', cnpj: '64.032.298/0001-02', city: 'Imbituba', tax: 'SIMPLES', activity: 'Serviço', payroll: 'Sim', active: true, initials: 'LR', tone: 'peach' },
    { name: 'Lineia Benvenuti', cnpj: '28.938.243/0001-94', city: 'Laguna', tax: 'MEI', activity: 'Comercio', payroll: 'Sim', active: true, initials: 'LB', tone: 'peach' },
    { name: 'Lucas Joao - J2 Colorir', cnpj: '35.587.663/0001-39', city: 'Imbituba', tax: 'SIMPLES', activity: 'Comércio E Serviço', payroll: 'Sim', active: true, initials: 'LJ', tone: 'mint' },
    { name: 'Luiza Rodrigues', cnpj: '39.394.167/0001-10', city: 'Imbituba', tax: 'SIMPLES', activity: 'Comércio E Serviço', payroll: 'Sim', active: true, initials: 'LR', tone: 'sand' },
    { name: 'Mardie Ambiental', cnpj: '62.322.783/0001-87', city: 'Imbituba', tax: 'SIMPLES', activity: 'Serviço', payroll: 'Sim', active: true, initials: 'MA', tone: '' },
    { name: 'Matheus Caetano', cnpj: '62.386.915/0001-34', city: 'Imbituba', tax: 'MEI', activity: 'Serviço', payroll: 'Não', active: true, initials: 'MC', tone: 'peach' },
    { name: 'Mercado Dona Salete', cnpj: '54.938.953/0001-24', city: 'Imbituba', tax: 'SIMPLES', activity: 'Comercio', payroll: 'Sim', active: true, initials: 'MD', tone: 'blue' },
    { name: 'Mercado Cucas', cnpj: '00.345.963/0001-27', city: 'Imbituba', tax: 'PRESUMIDO', activity: 'Comercio', payroll: 'Sim', active: true, initials: 'MC', tone: 'mint' },
    { name: 'Minimercado Dunas', cnpj: '42.701.678/0001-41', city: 'Imbituba', tax: 'SIMPLES', activity: 'Comercio', payroll: 'Não', active: true, initials: 'MD', tone: 'sand' },
    { name: 'Movplanej', cnpj: '33.105.117/0001-99', city: 'Imbituba', tax: 'PRESUMIDO', activity: 'Comércio E Serviço', payroll: 'Sim', active: true, initials: 'MO', tone: '' },
    { name: 'Neuronapse', cnpj: '51.375.454/0001-88', city: 'Tubarão', tax: 'PRESUMIDO', activity: 'Serviço', payroll: 'Sim', active: true, initials: 'NE', tone: 'peach' },
    { name: 'Opus Administradora', cnpj: '20.596.998/0001-46', city: 'Imbituba', tax: 'SIMPLES', activity: 'Serviço', payroll: 'Sim', active: true, initials: 'OA', tone: 'blue' },
    { name: 'Opus Prestadora De Serviços', cnpj: '64.784.570/0001-00', city: 'Imbituba', tax: 'SIMPLES', activity: 'Serviço', payroll: 'Não', active: true, initials: 'OP', tone: 'mint' },
    { name: 'Padaria Parada Doce', cnpj: '53.364.534/0001-63', city: 'Imbituba', tax: 'SIMPLES', activity: 'Comercio', payroll: 'Sim', active: true, initials: 'PP', tone: 'sand' },
    { name: 'Peixaria Lagoa Mar', cnpj: '37.240.189/0001-08', city: 'Imbituba', tax: 'MEI', activity: 'Comercio', payroll: 'Não', active: true, initials: 'PL', tone: 'peach' },
    { name: 'Progress Ramps', cnpj: '38.504.507/0001-55', city: 'Criciuma', tax: 'SIMPLES', activity: 'Comércio E Serviço', payroll: 'Não', active: true, initials: 'PR', tone: 'peach' },
    { name: 'Pousada Descanso Do Rei', cnpj: '02.001.721/0001-41', city: 'Imbituba', tax: 'SIMPLES', activity: 'Comércio E Serviço', payroll: 'Sim', active: true, initials: 'PD', tone: 'blue' },
    { name: 'Petronio', cnpj: '39.752.659/0001-30', city: 'Imbituba', tax: 'MEI', activity: 'Comércio E Serviço', payroll: 'Não', active: true, initials: 'PE', tone: 'peach' },
    { name: 'Rta Centro De Treinamento', cnpj: '59.650.723/0001-89', city: 'Imbituba', tax: 'SIMPLES', activity: 'Serviço', payroll: 'Sim', active: true, initials: 'RC', tone: 'sand' },
    { name: 'Rosane', cnpj: '61.903.819/0001-53', city: 'Imbituba', tax: 'MEI', activity: 'Serviço', payroll: 'Não', active: true, initials: 'RO', tone: 'peach' },
    { name: 'Rosana Papelaria', cnpj: '45.247.909/0001-87', city: 'Imbituba', tax: 'SIMPLES', activity: 'Comercio', payroll: 'Sim', active: true, initials: 'RP', tone: 'peach' },
    { name: 'Sa Construções', cnpj: '21.234.229/0001-60', city: 'Imbituba', tax: 'SIMPLES', activity: 'Serviço', payroll: 'Sim', active: true, initials: 'SC', tone: 'blue' },
    { name: 'Sidnei', cnpj: '65.190.635/0001-44', city: 'Blumenau', tax: 'SIMPLES', activity: 'Serviço', payroll: 'Não', active: true, initials: 'SI', tone: 'mint' },
    { name: 'Speed Visium', cnpj: '41.765.449/0001-28', city: 'Imbituba', tax: 'SIMPLES', activity: 'Comércio E Serviço', payroll: 'Sim', active: true, initials: 'SV', tone: 'sand' },
    { name: 'Storch Imports', cnpj: '12.230.415/0001-30', city: 'Imbituba', tax: 'SIMPLES', activity: 'Comércio E Serviço', payroll: 'Sim', active: true, initials: 'SI', tone: '' },
    { name: 'Studio Doufe', cnpj: '42.558.829/0001-54', city: 'Tubarão', tax: 'SIMPLES', activity: 'Serviço', payroll: 'Sim', active: true, initials: 'SD', tone: 'peach' },
    { name: 'Studio Rafa Mello', cnpj: '54.416.867/0001-51', city: 'Imbituba', tax: 'SIMPLES', activity: 'Serviço', payroll: 'Sim', active: true, initials: 'SR', tone: 'blue' },
    { name: 'Sthefany - Esposa Matheus', cnpj: '63.783.529/0001-49', city: 'Imbituba', tax: 'MEI', activity: 'Serviço', payroll: 'Não', active: true, initials: 'S-', tone: 'peach' },
    { name: 'Thamara Naiane Raquel', cnpj: '15.564.595/0001-85', city: 'Imbituba', tax: 'SIMPLES', activity: 'Comercio', payroll: 'Sim', active: true, initials: 'TN', tone: 'sand' },
    { name: 'Tennaro', cnpj: '57.866.944/0001-63', city: 'Garopaba', tax: 'SIMPLES', activity: 'Comercio', payroll: 'Não', active: true, initials: 'TE', tone: '' },
    { name: 'Theoweber', cnpj: '54.439.253/0001-95', city: 'Balneario Camboriu', tax: 'SIMPLES', activity: 'Comércio E Serviço', payroll: 'Sim', active: true, initials: 'TH', tone: 'peach' },
    { name: 'Vila Da Mata - Pousada', cnpj: '21.863.318/0001-76', city: 'Imbituba', tax: 'SIMPLES', activity: 'Serviço', payroll: 'Sim', active: true, initials: 'VD', tone: 'blue' },
    { name: 'Willian', cnpj: '33.800.043/0001-00', city: 'Imbituba', tax: 'SIMPLES', activity: 'Serviço', payroll: 'Sim', active: true, initials: 'WI', tone: 'mint' },
    { name: 'Cond. Bellas Artes', cnpj: '26.549.462/0001-56', city: 'Imbituba', tax: 'PRESUMIDO', activity: 'Condominio', payroll: 'Sim', active: true, initials: 'CB', tone: 'sand' },
    { name: 'Cond. Costa Da Lagoa', cnpj: '24.083.167/0001-21', city: 'Imbituba', tax: 'PRESUMIDO', activity: 'Condominio', payroll: 'Sim', active: true, initials: 'CC', tone: '' },
    { name: 'Cond. Di Capri', cnpj: '32.184.218/0001-30', city: 'Imbituba', tax: 'PRESUMIDO', activity: 'Condominio', payroll: 'Sim', active: true, initials: 'CD', tone: 'peach' },
    { name: 'Cond. Lagoa Azul', cnpj: '23.092.865/0001-20', city: 'Imbituba', tax: 'PRESUMIDO', activity: 'Condominio', payroll: 'Sim', active: true, initials: 'CL', tone: 'blue' },
    { name: 'Luis Brasiliense', cnpj: '5281096931.0', city: 'Imbituba', tax: 'Pf', activity: 'Pessoa Fisica', payroll: 'Sim', active: true, initials: 'LB', tone: 'mint' },
  ],
  departments: [
    { key: 'overview', label: 'Visão geral', detail: 'Acompanhar escritório', icon: '▦' },
    { key: 'fiscal', label: 'Fiscal', detail: 'Obrigações e guias', icon: '▤' },
    { key: 'pessoal', label: 'Pessoal', detail: 'Folha e eventos', icon: '♧' },
    { key: 'contabil', label: 'Contábil', detail: 'Movimentação e balancete', icon: '▣' },
    { key: 'societario', label: 'Societário', detail: 'Processos e procurações', icon: '▥' }
  ],
  departmentsData: {
    fiscal: { eyebrow: 'Obrigações e guias', intro: 'Controle as entregas fiscais por empresa, competência e canal de envio.', metric: '12', metricLabel: 'entregas no ciclo', tasks: [
      ['Importação das notas', 'Receber XML, validar período e organizar documentos.', 'Em andamento', 'Hoje', 'peach'], ['Apuração na Domínio', 'Conferir impostos e bases antes da transmissão.', 'Aguardando', '20 AGO', 'sand'], ['Transmissão PGDAS', 'Transmitir declaração e salvar protocolo do cliente.', 'Programada', '21 AGO', 'olive'], ['Envio da guia', 'Enviar por WhatsApp ou e-mail e registrar confirmação.', 'Aguardando', '22 AGO', 'blue'], ['Sintegra e DSTDA', 'Validar obrigações estaduais conforme atividade.', 'Aguardando', '25 AGO', 'sand'], ['Livro eletrônico e EFD Reinf', 'Revisar arquivos, recibos e pendências de retorno.', 'Aguardando', '27 AGO', 'olive'], ['DEFIS anual', 'Acompanhar documentação e fechamento anual.', 'Anual', 'Março', 'blue']
    ] },
    pessoal: { eyebrow: 'Folha e eventos', intro: 'Organize a folha, eventos trabalhistas e as comunicações de cada competência.', metric: '08', metricLabel: 'pontos na folha', tasks: [
      ['Conferir anotações', 'Revisar alterações, empréstimos e apontamentos do período.', 'Em andamento', 'Hoje', 'peach'], ['Cálculo da folha', 'Processar folha e conferir bases, descontos e líquidos.', 'Aguardando', '23 AGO', 'olive'], ['Eventos para eSocial', 'Enviar eventos e acompanhar retornos do ambiente.', 'Aguardando', '24 AGO', 'blue'], ['Fechamento DCTFWeb', 'Conferir fechamento, débitos e recibos da competência.', 'Programada', '25 AGO', 'sand'], ['Recibos e guias', 'Gerar documentos e enviar por WhatsApp ou e-mail.', 'Aguardando', '26 AGO', 'olive'], ['Admissões, férias e rescisões', 'Registrar movimentações e prazos dos colaboradores.', 'Contínuo', 'Sempre', 'peach'], ['Atestados e procedimentos', 'Manter anotações da folha e próximos procedimentos.', 'Contínuo', 'Sempre', 'blue'], ['Distribuição de lucros e EFD Reinf', 'Alinhar com Contábil e acompanhar eventos da folha.', 'Aguardando', '28 AGO', 'sand']
    ] },
    contabil: { eyebrow: 'Movimentação e balancete', intro: 'Registre a documentação contábil recebida e acompanhe o fechamento de cada empresa.', metric: '04', metricLabel: 'fechamentos ativos', tasks: [
      ['Solicitar movimentação', 'Enviar solicitação e registrar documentos pendentes.', 'Em andamento', 'Hoje', 'peach'], ['Importar extratos', 'Organizar extratos bancários e conferir período.', 'Aguardando', '22 AGO', 'blue'], ['Distribuição de lucros', 'Verificar valores e alinhar documentação com a empresa.', 'Aguardando', '26 AGO', 'sand'], ['Fechamento do balancete', 'Conferir lançamentos e concluir balancete mensal.', 'Programada', '30 AGO', 'olive']
    ] },
    societario: { eyebrow: 'Processos e procurações', intro: 'Acompanhe os processos societários, vínculos e documentos legais por empresa.', metric: '06', metricLabel: 'processos ativos', tasks: [
      ['Cadastro das empresas', 'Manter dados cadastrais e documentos do sistema atualizados.', 'Em andamento', 'Hoje', 'peach'], ['Procurações', 'Controlar validade, poderes e responsáveis por cada procuração.', 'Aguardando', '22 AGO', 'sand'], ['Vínculo SAT e CRC', 'Confirmar vínculos e acessos necessários para atendimento.', 'Aguardando', '24 AGO', 'blue'], ['Abertura de CNPJ', 'Acompanhar etapas, documentos e protocolos de abertura.', 'Programada', '27 AGO', 'olive'], ['Baixa e alteração', 'Organizar processos, exigências e retornos dos órgãos.', 'Aguardando', '30 AGO', 'peach']
    ] }
  }
};
