/* Corrêa Controle Interno — JavaScript puro, sem bibliotecas. */
const clients=[
 {name:'Alvorada Comércio de Alimentos',cnpj:'12.345.678/0001-90',city:'São Paulo, SP',tax:'SIMPLES',activity:'Comércio varejista',payroll:'Sim',active:true,initials:'AC',tone:''},
 {name:'Ateliê Linha & Forma',cnpj:'45.678.901/0001-23',city:'Campinas, SP',tax:'PRESUMIDO',activity:'Serviços de design',payroll:'Não',active:true,initials:'LF',tone:'peach'},
 {name:'Brava Tecnologia',cnpj:'23.456.789/0001-45',city:'Belo Horizonte, MG',tax:'REAL',activity:'Tecnologia da informação',payroll:'Sim',active:true,initials:'BT',tone:'blue'},
 {name:'Café do Largo',cnpj:'78.901.234/0001-56',city:'Jundiaí, SP',tax:'MEI',activity:'Alimentação',payroll:'Não',active:false,initials:'CL',tone:'peach'},
 {name:'Mosaico Arquitetura',cnpj:'34.567.890/0001-12',city:'Santos, SP',tax:'SIMPLES',activity:'Arquitetura e urbanismo',payroll:'Sim',active:true,initials:'MA',tone:'mint'}
];
const departments=[
 {key:'overview',label:'Visão geral',detail:'Acompanhar escritório',icon:'▦'},
 {key:'fiscal',label:'Fiscal',detail:'Obrigações e guias',icon:'▤'},
 {key:'pessoal',label:'Pessoal',detail:'Folha e eventos',icon:'♧'},
 {key:'contabil',label:'Contábil',detail:'Movimentação e balancete',icon:'▣'},
 {key:'societario',label:'Societário',detail:'Processos e procurações',icon:'▥'}
];
const modules={
 fiscal:{eyebrow:'Obrigações e guias',intro:'Controle as entregas fiscais por empresa, competência e canal de envio.',metric:'12',metricLabel:'entregas no ciclo',tasks:[
  ['Importação das notas','Receber XML, validar período e organizar documentos.','Em andamento','Hoje','peach'],['Apuração na Domínio','Conferir impostos e bases antes da transmissão.','Aguardando','20 AGO','sand'],['Transmissão PGDAS','Transmitir declaração e salvar protocolo do cliente.','Programada','21 AGO','olive'],['Envio da guia','Enviar por WhatsApp ou e-mail e registrar confirmação.','Aguardando','22 AGO','blue'],['Sintegra e DSTDA','Validar obrigações estaduais conforme atividade.','Aguardando','25 AGO','sand'],['Livro eletrônico e EFD Reinf','Revisar arquivos, recibos e pendências de retorno.','Aguardando','27 AGO','olive'],['DEFIS anual','Acompanhar documentação e fechamento anual.','Anual','Março','blue']]},
 pessoal:{eyebrow:'Folha e eventos',intro:'Organize a folha, eventos trabalhistas e as comunicações de cada competência.',metric:'08',metricLabel:'pontos na folha',tasks:[
  ['Conferir anotações','Revisar alterações, empréstimos e apontamentos do período.','Em andamento','Hoje','peach'],['Cálculo da folha','Processar folha e conferir bases, descontos e líquidos.','Aguardando','23 AGO','olive'],['Eventos para eSocial','Enviar eventos e acompanhar retornos do ambiente.','Aguardando','24 AGO','blue'],['Fechamento DCTFWeb','Conferir fechamento, débitos e recibos da competência.','Programada','25 AGO','sand'],['Recibos e guias','Gerar documentos e enviar por WhatsApp ou e-mail.','Aguardando','26 AGO','olive'],['Admissões, férias e rescisões','Registrar movimentações e prazos dos colaboradores.','Contínuo','Sempre','peach'],['Atestados e procedimentos','Manter anotações da folha e próximos procedimentos.','Contínuo','Sempre','blue'],['Distribuição de lucros e EFD Reinf','Alinhar com Contábil e acompanhar eventos da folha.','Aguardando','28 AGO','sand']]},
 contabil:{eyebrow:'Movimentação e balancete',intro:'Registre a documentação contábil recebida e acompanhe o fechamento de cada empresa.',metric:'04',metricLabel:'fechamentos ativos',tasks:[
  ['Solicitar movimentação','Enviar solicitação e registrar documentos pendentes.','Em andamento','Hoje','peach'],['Importar extratos','Organizar extratos bancários e conferir período.','Aguardando','22 AGO','blue'],['Distribuição de lucros','Verificar valores e alinhar documentação com a empresa.','Aguardando','26 AGO','sand'],['Fechamento do balancete','Conferir lançamentos e concluir balancete mensal.','Programada','30 AGO','olive']]},
 societario:{eyebrow:'Processos e procurações',intro:'Acompanhe os processos societários, vínculos e documentos legais por empresa.',metric:'06',metricLabel:'processos ativos',tasks:[
  ['Cadastro das empresas','Manter dados cadastrais e documentos do sistema atualizados.','Em andamento','Hoje','peach'],['Procurações','Controlar validade, poderes e responsáveis por cada procuração.','Aguardando','22 AGO','sand'],['Vínculo SAT e CRC','Confirmar vínculos e acessos necessários para atendimento.','Aguardando','24 AGO','blue'],['Abertura de CNPJ','Acompanhar etapas, documentos e protocolos de abertura.','Programada','27 AGO','olive'],['Baixa e alteração','Organizar processos, exigências e retornos dos órgãos.','Aguardando','30 AGO','peach']]}
};
let currentPage=getPageFromUrl();let selectedClient=clients[0];let activeOnly=true;
function getPageFromUrl(){const page=location.hash.replace('#/','');return departments.some(d=>d.key===page)?page:'overview'}
function navigate(page){currentPage=page;location.hash=page==='overview'?'':'/'+page;render()}
function renderNav(){document.querySelector('#department-nav').innerHTML=departments.map(d=>`<button class="${currentPage===d.key?'active':''}" data-page="${d.key}"><span class="nav-icon">${d.icon}</span><span class="nav-copy"><strong>${d.label}</strong><small>${d.detail}</small></span>${currentPage===d.key?'<i class="active-mark"></i>':''}</button>`).join('');document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.page)))}
function render(){renderNav();document.querySelector('#page-title').textContent=currentPage==='overview'?'Bom dia, Ihara':`Departamento ${departments.find(d=>d.key===currentPage).label}`;document.querySelector('#page-content').innerHTML=currentPage==='overview'?overviewHtml():departmentHtml(currentPage);bindEvents()}
function overviewHtml(){return `<section class="paper-card"><div class="hero-copy"><p class="eyebrow">Visão do escritório</p><h2>O trabalho de hoje,<br><span>organizado por cliente.</span></h2><p>Centralize as rotinas dos quatro departamentos e encontre rapidamente o próximo passo de cada empresa.</p><button class="primary-button" data-action="new-client">＋ Cadastrar cliente</button></div></section><section class="summary-grid"><div class="summary-card"><div class="summary-icon">▥</div><label>Empresas ativas</label><div class="summary-value">04 <small>de 05 cadastradas</small></div></div><div class="summary-card"><div class="summary-icon">☑</div><label>Rotinas em dia</label><div class="summary-value">86% <small>+8% este mês</small></div></div><div class="summary-card"><div class="summary-icon">!</div><label>Pontos de atenção</label><div class="summary-value">07 <small>2 vencem hoje</small></div></div><div class="summary-card"><div class="summary-icon">▦</div><label>Próximo fechamento</label><div class="summary-value">28 AGO <small>Folha mensal</small></div></div></section>${clientsHtml()}${lowerHtml()}`}
function clientsHtml(){return `<section><div class="section-heading"><div><p class="eyebrow">Base de clientes</p><h2>Empresas acompanhadas</h2></div><button class="text-button" data-action="new-client">＋ Adicionar cliente</button></div><div class="client-table"><div class="table-tools"><div class="search-wrap"><span>⌕</span><input id="client-search" placeholder="Buscar por empresa, CNPJ ou cidade"></div><button id="active-filter" class="filter-button ${activeOnly?'':'all'}">${activeOnly?'Somente ativos':'Todos os clientes'}</button></div><div class="table-scroll"><table><thead><tr><th>Cliente</th><th>CNPJ</th><th>Cidade</th><th>Tributação</th><th>Atividade</th><th>Folha</th><th>Status</th><th></th></tr></thead><tbody id="client-rows">${clientRows()}</tbody></table></div></div></section>`}
function clientRows(){const q=(document.querySelector('#client-search')?.value||'').toLowerCase();return clients.filter(c=>(!activeOnly||c.active)&&`${c.name} ${c.cnpj} ${c.city}`.toLowerCase().includes(q)).map(c=>`<tr class="${selectedClient.cnpj===c.cnpj?'selected':''}" data-client="${c.cnpj}"><td><div class="client-name"><span class="initials ${c.tone}">${c.initials}</span>${c.name}</div></td><td>${c.cnpj}</td><td>${c.city}</td><td><span class="tag">${c.tax}</span></td><td>${c.activity}</td><td>${c.payroll}</td><td><span class="status ${c.active?'':'inactive'}"><i></i>${c.active?'Ativo':'Inativo'}</span></td><td>↗</td></tr>`).join('')||'<tr><td colspan="8" style="text-align:center;padding:30px">Nenhum cliente encontrado.</td></tr>'}
function lowerHtml(){return `<section class="lower-grid"><div class="panel"><p class="eyebrow">Rotinas por setor</p><h3>Mapa de acompanhamento</h3>${[['Fiscal','82%'],['Pessoal','64%'],['Contábil','91%'],['Societário','48%']].map(x=>`<div class="progress-row"><label>${x[0]}</label><div class="progress-bar"><i style="width:${x[1]}"></i></div><span>${x[1]}</span></div>`).join('')}</div><div class="panel client-focus"><p class="eyebrow">Cliente selecionado</p><h4>${selectedClient.name}</h4><small>${selectedClient.city} · ${selectedClient.tax}</small><div class="focus-stats"><div class="focus-stat"><small>Pendências</small><strong>03</strong></div><div class="focus-stat"><small>Em dia</small><strong>18</strong></div></div><button class="text-button" data-action="toast" data-message="A ficha completa será habilitada na próxima etapa.">Ver ficha completa ↗</button></div></section>`}
function departmentHtml(key){const d=departments.find(x=>x.key===key),m=modules[key];return `<section class="dept-hero"><p class="eyebrow">${m.eyebrow}</p><h2>Departamento ${d.label}</h2><p>${m.intro}</p><div class="client-context"><p class="eyebrow">Cliente em foco</p><strong>${selectedClient.name}</strong><small>${m.metric} ${m.metricLabel}</small></div></section><div class="routine-heading"><div><p class="eyebrow">Checklist do departamento</p><h2>Rotinas e próximos prazos</h2></div><button class="primary-button" data-action="toast" data-message="A nova rotina será criada na próxima etapa.">＋ Nova rotina</button></div><section class="routine-grid">${m.tasks.map(t=>`<button class="routine-card" data-action="toast" data-message="${t[0]}: acompanhamento aberto para ${selectedClient.name}."><div class="routine-top"><span class="routine-status ${t[4]}">${t[2]}</span><span class="due">${t[3]}</span></div><h4>${t[0]}</h4><p>${t[1]}</p><div class="routine-footer"><span>${selectedClient.initials} · ${selectedClient.tax}</span><span>↗</span></div></button>`).join('')}</section>${clientsHtml()}${lowerHtml()}`}
function bindEvents(){document.querySelectorAll('[data-action="toast"]').forEach(el=>el.addEventListener('click',()=>toast(el.dataset.message)));document.querySelectorAll('[data-action="new-client"]').forEach(el=>el.addEventListener('click',showModal));const search=document.querySelector('#client-search');if(search)search.addEventListener('input',()=>{document.querySelector('#client-rows').innerHTML=clientRows();bindClientRows()});const filter=document.querySelector('#active-filter');if(filter)filter.addEventListener('click',()=>{activeOnly=!activeOnly;render()});bindClientRows()}
function bindClientRows(){document.querySelectorAll('[data-client]').forEach(row=>row.addEventListener('click',()=>{selectedClient=clients.find(c=>c.cnpj===row.dataset.client);render()}))}
function showModal(){document.querySelector('#modal-root').innerHTML=`<div class="modal-backdrop" id="modal-backdrop"><div class="modal"><div class="modal-header"><div><p class="eyebrow">Nova ficha</p><h2>Cadastrar cliente</h2><p style="font-size:12px;color:#7D8579">A primeira etapa para acompanhar as rotinas por setor.</p></div><button class="close" id="close-modal">×</button></div><div class="form-grid"><div class="form-field wide"><label>Razão social</label><input placeholder="Nome da empresa"></div><div class="form-field"><label>CNPJ</label><input placeholder="00.000.000/0000-00"></div><div class="form-field"><label>Cidade</label><input placeholder="Cidade / UF"></div><div class="form-field"><label>Tributação</label><input placeholder="Selecionar"></div><div class="form-field wide"><label>Atividade principal</label><input placeholder="Descreva a atividade"></div></div><div class="modal-actions"><button class="secondary-button" id="cancel-modal">Cancelar</button><button class="primary-button" id="save-modal" style="margin:0">Salvar rascunho</button></div></div></div>`;document.querySelector('#close-modal').onclick=closeModal;document.querySelector('#cancel-modal').onclick=closeModal;document.querySelector('#save-modal').onclick=()=>{closeModal();toast('Ficha criada como rascunho. Conecte o banco de dados para persistir o cadastro.')}}
function closeModal(){document.querySelector('#modal-root').innerHTML=''}
function toast(message){const root=document.querySelector('#toast-root');root.innerHTML=`<div class="toast">${message}</div>`;setTimeout(()=>root.innerHTML='',3200)}
window.addEventListener('hashchange',()=>{currentPage=getPageFromUrl();render()});render();
